<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mca</string>
		<string>mcassembly</string>
	</array>
	<key>name</key>
	<string>MCAssembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single-line comments</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.mca</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>multi-line comments</string>
			<key>contentName</key>
			<string>comment.block.documentation.mca</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.mca</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Commands</string>
			<key>end</key>
			<string>(;|\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedCharacters</string>
				</dict>
				<dict>
					<key>comment</key>
					<dict>
						<key>insertions</key>
						<false/>
					</dict>
					<key>match</key>
					<string>{\s*.+\s*}</string>
					<key>name</key>
					<string>string.interpolated.mca</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control statements</string>
			<key>match</key>
			<string>\b[Ii][Ff]|[Ww][Hh][Ii][Ll][Ee]|[Rr][Ee][Tt][Uu][Rr][Nn]|[Oo][Uu][Tt]\b</string>
			<key>name</key>
			<string>keyword.control.mca</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#?\w+)\s*(\()(.*)(\))\s*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mca</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.mca</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mca</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.mca</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Macro function definitions, and anonymous branch creation</string>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Blocks</string>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single quoted strings</string>
			<key>contentName</key>
			<string>string.quoted.single.mca</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.mca</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedCharacters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double quoted strings</string>
			<key>contentName</key>
			<string>string.quoted.double.mca</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mca</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedCharacters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(?:\d*\.)?\d+</string>
			<key>name</key>
			<string>constant.numeric.mca</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\.\w+)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.mca</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Internal function calls</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#?\w+)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mca</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Macro function calls</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>TRUE boolean constant</string>
			<key>match</key>
			<string>[Tt][Rr][Uu][Ee]</string>
			<key>name</key>
			<string>constant.language.boolean.true</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FALSE boolean constant</string>
			<key>match</key>
			<string>[Ff][Aa][Ll][Ss][Ee]</string>
			<key>name</key>
			<string>constant.language.boolean.false</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>==|!=|&gt;|&lt;|&gt;=|&lt;=|!|\|\|</string>
			<key>name</key>
			<string>keyword.operator.mca</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Brackets</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.mca</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assign operator (set variable to value)</string>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.mca</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Semicolons</string>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.control.mca</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Anything that is not a word</string>
			<key>match</key>
			<string>[^\w\s,]</string>
			<key>name</key>
			<string>invalid.illegal.mca</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escapedCharacters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Escaped characters such as \w</string>
					<key>match</key>
					<string>\\\w+</string>
					<key>name</key>
					<string>constant.character.escape.mca</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mca</string>
	<key>uuid</key>
	<string>be27af90-c373-4e32-9161-5f3ab1d70a3c</string>
</dict>
</plist>
